# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0010_update_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagSeguroConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='account email')),
                ('token', models.CharField(max_length=32, verbose_name='account token')),
                ('sandbox', models.BooleanField(default=False, help_text='Enable this to activate Developer mode (testing).', verbose_name='Sandbox mode')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagseguro_config', to='shuup.Shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name_plural': 'PagSeguro configurations',
                'verbose_name': 'PagSeguro configuration',
            },
        ),
        migrations.CreateModel(
            name='PagSeguroPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='pagseguro data')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuup.Order', verbose_name='order')),
            ],
            options={
                'verbose_name_plural': 'PagSeguro payments',
                'verbose_name': 'PagSeguro payments',
            },
        ),
        migrations.CreateModel(
            name='PagSeguroPaymentProcessor',
            fields=[
                ('paymentprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup.PaymentProcessor')),
            ],
            options={
                'verbose_name_plural': 'PagSeguro',
                'verbose_name': 'PagSeguro',
            },
            bases=('shuup.paymentprocessor',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
