# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_pagseguro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagseguropayment',
            name='code',
            field=models.CharField(max_length=40, verbose_name='code'),
        ),
    ]
